language: php

branches:
  only:
    - master

env:
  global:
    - WP_VERSION=latest
    - WP_MULTISITE=0
    - TEST_BUILD_DIR=${TRAVIS_BUILD_DIR}
    - INSTALL_PHPUNIT=true
    - DB_HOST=localhost
    - PATH=${HOME}/bin:${PATH}

matrix:
  include:
    - php: 5.6
      env: RUN_CS_FIXER=true
    - php: 7.0
    - php: 7.1

before_install:
  - pushd ${HOME}
